export const blockTypes = [
    "Box",
    "Columns",
    "grid",
    "section",
    "text",
    "image",
    "map-block",
    "video-block",
    "ecommerce",
    "modal",
    "tooltip",
    "form",
    "input",
    "textarea",
    "select",
    "button",
    "label",
    "checkbox",
    "radio",
    "custom-code",
    "tabs",
    "lory-slider",
    "typed",
    "bars-chart",
    "pie-chart",
    "donut-chart",
    "lines-chart",
    "custom-chart",
    "googleAnalytics",
    /*"My Custom Columns",
    "blocker",
    "My Cool Section",
    "Super Section",
    "My image block",
    "ll",
    "Blook",
    "Super Box",
    "textblook",
    "helveticablock",
    ",.mlmlmlm"*/
]